<a href="https://colab.research.google.com/github/ArmandoBarrios/unidad-3-/blob/main/Unidad3_practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importar Librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
#Carga el Dataset
from google.colab import drive
drive.mount('/content/drive')
#ID del archivo
#https:https://drive.google.com/file/d/10jb6-kPt9b-03nwtI_ll8CQeruX1LmZj/view?usp=sharing
file_id = '10jb6-kPt9b-03nwtI_ll8CQeruX1LmZj'
url =  f"https://drive.google.com/uc?id={file_id}"

#cargas Datos
df = pd.read_csv(url)
df.head()

Mounted at /content/drive


,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192,8.4,7.3,0.55
1,1,apple,granny_smith,180,8.0,6.8,0.59
2,1,apple,granny_smith,176,7.4,7.2,0.60
3,2,mandarin,mandarin,86,6.2,4.7,0.80
4,2,mandarin,mandarin,84,6.0,4.6,0.79


#Seleccion de Variables predictoras (x) y Variables a predecir (y)

In [2]:
# Limpiar nombres de columnas
df.columns = df.columns.str.strip()

# Selección de variables
X = df[['height', 'width', 'mass', 'color_score']]
y = df['fruit_name']

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [4]:
clasificador_KNN = KNeighborsClassifier(n_neighbors=1)
clasificador_KNN.fit(X_train, y_train)

print("Precision entrenamiento:", clasificador_KNN.score(X_train, y_train))


Precision entrenamiento: 1.0


In [5]:
y_pred = clasificador_KNN.predict(X_test)

print(classification_report(y_test, y_pred))
print("Precisión:", clasificador_KNN.score(X_test, y_test))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

       apple       0.00      0.00      0.00         4
       lemon       1.00      0.60      0.75         5
    mandarin       1.00      1.00      1.00         2
      orange       0.38      0.75      0.50         4

    accuracy                           0.53        15
   macro avg       0.59      0.59      0.56        15
weighted avg       0.57      0.53      0.52        15

Precisión: 0.5333333333333333
[[0 0 0 4]
 [1 3 0 1]
 [0 0 2 0]
 [1 0 0 3]]


In [6]:
from sklearn.inspection import permutation_importance

result = permutation_importance(clasificador_KNN, X_test, y_test, n_repeats=30, random_state=42)

importancia = pd.DataFrame({
    "Variable": X.columns,
    "Importancia Media": result.importances_mean,
    "Desviación": result.importances_std
}).sort_values("Importancia Media", ascending=False)

importancia

,Variable,Importancia Media,Desviación
2,mass,0.266667,0.095839
3,color_score,-0.004444,0.016630
0,height,-0.028889,0.063674
1,width,-0.062222,0.048483


In [7]:
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
              error_y="Desviación", title="Importancia (KNN)",
              text_auto=".3f", color="Variable")
fig4.show()

In [8]:
clasificador_KNN3 = KNeighborsClassifier(n_neighbors=3)
clasificador_KNN3.fit(X_train, y_train)

y_pred = clasificador_KNN3.predict(X_test)

print(classification_report(y_test, y_pred))
print("Precisión:", clasificador_KNN3.score(X_test, y_test))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

       apple       0.67      0.50      0.57         4
       lemon       0.50      0.40      0.44         5
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.75      0.60         4

    accuracy                           0.60        15
   macro avg       0.67      0.66      0.65        15
weighted avg       0.61      0.60      0.59        15

Precisión: 0.6
[[2 1 0 1]
 [1 2 0 2]
 [0 0 2 0]
 [0 1 0 3]]


In [9]:
clasificador_KNN5 = KNeighborsClassifier(n_neighbors=5)
clasificador_KNN5.fit(X_train, y_train)

y_pred = clasificador_KNN5.predict(X_test)

print(classification_report(y_test, y_pred))
print("Precisión:", clasificador_KNN5.score(X_test, y_test))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

       apple       0.67      0.50      0.57         4
       lemon       0.50      0.40      0.44         5
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.75      0.60         4

    accuracy                           0.60        15
   macro avg       0.67      0.66      0.65        15
weighted avg       0.61      0.60      0.59        15

Precisión: 0.6
[[2 1 0 1]
 [1 2 0 2]
 [0 0 2 0]
 [0 1 0 3]]


In [10]:
for k in range(1, 20):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    print(f"k={k} → Precisión: {knn.score(X_test, y_test):.2f}")


k=1 → Precisión: 0.53
k=2 → Precisión: 0.53
k=3 → Precisión: 0.60
k=4 → Precisión: 0.60
k=5 → Precisión: 0.60
k=6 → Precisión: 0.40
k=7 → Precisión: 0.60
k=8 → Precisión: 0.53
k=9 → Precisión: 0.53
k=10 → Precisión: 0.53
k=11 → Precisión: 0.47
k=12 → Precisión: 0.47
k=13 → Precisión: 0.47
k=14 → Precisión: 0.47
k=15 → Precisión: 0.40
k=16 → Precisión: 0.40
k=17 → Precisión: 0.40
k=18 → Precisión: 0.47
k=19 → Precisión: 0.40


In [11]:
from sklearn.preprocessing import StandardScaler


X = df[["height", "width", "mass", "color_score"]]
y = df["fruit_name"]

# División con stratify
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y
)

# Escalado
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = knn_scaled.predict(X_test_scaled)

print(classification_report(y_test, y_pred_scaled))
print(confusion_matrix(y_test, y_pred_scaled))


              precision    recall  f1-score   support

       apple       1.00      0.80      0.89         5
       lemon       1.00      1.00      1.00         4
    mandarin       1.00      1.00      1.00         1
      orange       0.83      1.00      0.91         5

    accuracy                           0.93        15
   macro avg       0.96      0.95      0.95        15
weighted avg       0.94      0.93      0.93        15

[[4 0 0 1]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 5]]


In [13]:
result = permutation_importance(knn_scaled, X_test_scaled, y_test, n_repeats=30, random_state=42)

importancia = pd.DataFrame({
    "Variable": X.columns,
    "Importancia Media": result.importances_mean,
    "Desviación": result.importances_std
}).sort_values("Importancia Media", ascending=False)

importancia

,Variable,Importancia Media,Desviación
0,height,0.262222,0.080615
1,width,0.188889,0.075195
3,color_score,0.182222,0.103184
2,mass,0.037778,0.061303


In [14]:
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
              error_y="Desviación", title="Importancia escalada",
              text_auto=".3f", color="Variable")
fig4.show()


In [15]:
fruta1 = [[5.5, 2.2, 150, 0.70]]
print(knn_scaled.predict(fruta1))

frutas_nuevas = [[5.5, 2.2, 120, 0.70], [2, 2, 160, 0.50]]
print(knn_scaled.predict(frutas_nuevas))


['orange']
['orange' 'orange']
